export class RouterName {
  public static readonly Home = 'Home'
  public static readonly MessageList = 'MessageList'
  public static readonly Conversation = 'Conversation'
  public static readonly CharacterCard = 'CharacterCard'
  public static readonly CharacterCardDetail = 'CharacterCardDetail'
  public static readonly WorldBook = 'WorldBook'
  public static readonly WorldBookDetail = 'WorldBookDetail'
  public static readonly WorldInfoEntryEdit = 'WorldInfoEntryEdit'
  public static readonly CharacterCardEdit = 'CharacterCardEdit'
  public static readonly Settings = 'Settings'
  public static readonly ProviderList = 'ProviderList'
  public static readonly ProviderEdit = 'ProviderEdit'
}
