export class RouterName {
  public static readonly Home = 'Home'
  public static readonly Message = 'Message'
  public static readonly CharacterCard = 'CharacterCard'
  public static readonly WorldBook = 'WorldBook'
  public static readonly AddCharacterCard = 'AddCharacterCard'
  public static readonly Settings = 'Settings'
  public static readonly ModelProviderList = 'ModelProviderList'
  public static readonly ModelProviderEdit = 'ModelProviderEdit'
}